### ISSUE TITLE
在elipse中启动的时候报错

### ISSUE THREAD

**Issue by zhangyz11** [wuweiit/AliceBot#1]
在elipse中启动的时候报错 ，lucene报错但是，我没有找到要写lucene索引文件的地方，只是在调用数据库的时候才会出现这个问题，是不是这个功能目前没有完成，如果在robot.properties中将DBAvailable改为false可以执行。但是只能读取aimi文件，无法做到索引文件一起使用
具体报错如下：
四月 08, 2018 10:56:33 上午 org.ansj.util.MyStaticValue <clinit>
警告: not find library.properties in classpath use it by default !
四月 08, 2018 10:56:33 上午 org.ansj.library.UserDefineLibrary loadLibrary
警告: init userLibrary  waring :library/default.dic because : not find that file or can not to read !
四月 08, 2018 10:56:33 上午 org.ansj.library.UserDefineLibrary initAmbiguityLibrary
警告: init ambiguity  waring :library/ambiguity.dic because : not find that file or can not to read !
四月 08, 2018 10:56:34 上午 org.ansj.library.InitDictionary init
信息: init core library ok use time :1085
四月 08, 2018 10:56:35 上午 org.ansj.library.NgramLibrary <clinit>
信息: init ngram ok use time :806
org.apache.lucene.index.IndexNotFoundException: no segments* file found in MMapDirectory@D:\alicebot\AliceBot\Index lockFactory=org.apache.lucene.store.NativeFSLockFactory@2cb4c3ab: files: [write.lock]
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:637)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:50)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
	at com.aiml.IndexResource.buildIndexReader(IndexResource.java:70)
	at com.aiml.IndexResource.init(IndexResource.java:36)
	at com.aiml.IndexResource.<init>(IndexResource.java:29)
	at com.aiml.IndexResource.getInstance(IndexResource.java:117)
	at com.aiml.IndexSearchService.<init>(IndexSearchService.java:21)
	at com.aiml.AskToDB.<init>(AskToDB.java:11)
	at com.context.ChartManager.<init>(ChartManager.java:19)
	at com.context.ChartManager.getInstance(ChartManager.java:27)
	at com.context.Robot.<init>(Robot.java:14)
	at com.context.Robot.main(Robot.java:23)
Exception in thread "main" java.lang.NullPointerException
	at org.apache.lucene.search.IndexSearcher.<init>(IndexSearcher.java:120)
	at org.apache.lucene.search.IndexSearcher.<init>(IndexSearcher.java:105)
	at com.aiml.IndexResource.buildIndexSearcher(IndexResource.java:84)
	at com.aiml.IndexResource.init(IndexResource.java:37)
	at com.aiml.IndexResource.<init>(IndexResource.java:29)
	at com.aiml.IndexResource.getInstance(IndexResource.java:117)
	at com.aiml.IndexSearchService.<init>(IndexSearchService.java:21)
	at com.aiml.AskToDB.<init>(AskToDB.java:11)
	at com.context.ChartManager.<init>(ChartManager.java:19)
	at com.context.ChartManager.getInstance(ChartManager.java:27)
	at com.context.Robot.<init>(Robot.java:14)
	at com.context.Robot.main(Robot.java:23)

**Comment by wuweiit** [comment]
问题已经处理了，拉最新代码吧。
然后索引这款都自己改哦。

**Comment by zhangyz11** [comment]
多谢
